[package]
name = "dill"
version = "0.1.0"
authors = ["DanMass <damass@microsoft.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
prost = "0.8"
prost-types = "0.8"
tonic = "0.5.2"

[build-dependencies]
tonic-build = "0.5.2"