# pickle root
GET http://localhost:30088 HTTP/1.1

###

# pickle v1.0 openapi description
GET http://localhost:30088/api/v1.0/openapi.json HTTP/1.1

###

# pickle v1.0 default words list
GET http://localhost:30088/api/v1.0/words HTTP/1.1

###

# pickle v1.0 words list for count
GET http://localhost:30088/api/v1.0/words?count=7 HTTP/1.1

###

# pickle v1.0 words list for count and signed
GET http://localhost:30088/api/v1.0/words?count=4&signed HTTP/1.1

###

# pickle v1.0 default words list
POST http://localhost:30088/api/v1.0/sign HTTP/1.1
content-type: application/json

{
    "words": ["parched", "overcondfident", "fascinated", "rusty", "opossum"]
}
