apiVersion: v1
kind: Namespace
metadata:
  name: pickle
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weber
  namespace: pickle
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worder
  namespace: pickle
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: signer
  namespace: pickle
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: pickle
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: web-svc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: words-svc
  namespace: pickle
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 9090
  selector:
    app: words-svc
---
apiVersion: v1
kind: Service
metadata:
  name: signing-svc
  namespace: pickle
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 9090
  selector:
    app: signing-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: pickle
    app.kubernetes.io/version: v11
  name: web
  namespace: pickle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
      version: v11
  template:
    metadata:
      labels:
        app: web-svc
        version: v11
    spec:
      containers:
      - image: pickle:local
        name: web-svc
        ports:
        - containerPort: 8000
          name: http
      serviceAccountName: weber
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: words
    app.kubernetes.io/part-of: pickle
    app.kubernetes.io/version: v11
  name: words
  namespace: pickle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: words-svc
      version: v11
  template:
    metadata:
      labels:
        app: words-svc
        version: v11
    spec:
      containers:
      - image: pickle_depa:local
        name: words-svc
        ports:
        - containerPort: 9090
          name: grpc
      serviceAccountName: worder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: signing
    app.kubernetes.io/part-of: pickle
    app.kubernetes.io/version: v11
  name: signing
  namespace: pickle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signing-svc
      version: v11
  template:
    metadata:
      labels:
        app: signing-svc
        version: v11
    spec:
      containers:
      - image: pickle_depb:local
        name: signing-svc
      serviceAccountName: signer
