[package]
name = "pickle"
version = "0.1.0"
authors = ["Dan Massey <danmass@microsoft.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
