version: "3.9"
services:
  pickle:
    build:
      context: .
      dockerfile: pickle.Dockerfile
  depa:
    build:
      context: .
      dockerfile: depa.Dockerfile
  depb:
    build:
      context: .
      dockerfile: depb.Dockerfile
