version: "3.9"
services:
  pickle:
    image: pickle:local
    build:
      context: .
      dockerfile: pickle.Dockerfile
  words:
    image: pickle_words:local
    build:
      context: .
      dockerfile: words.Dockerfile
  signer:
    image: pickle_signer:local
    build:
      context: .
      dockerfile: signer.Dockerfile
