apiVersion: v1
kind: Pod
metadata:
  name: pickle
  labels:
    app: pickle

spec:
  containers:
  - name: app
    imagePullPolicy: Always
    image: k3d-registry.localhost:5000/pickle:local
    ports:
    - containerPort: 8000
    resources:
      requests:
        memory: "100Mi"
        cpu: "500m"
      limits:
        memory: "200Mi"
        cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: pickle
  labels:
    app: pickle
spec:
  type: NodePort
  selector:
    app: pickle
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30088
