ingressClass:
  enabled: true

providers:
  kubernetesCRD:
    namespaces:
      - default
      - pickle
  kubernetesIngress:
    namespaces:
      - default
      - pickle

deployment:
    annotations:
      linkerd.io/inject: ingress
      config.linkerd.io/trace-collector: collector.linkerd-jaeger:55678
      config.alpha.linkerd.io/trace-collector-service-account: collector

additionalArguments:
 - "--tracing.jaeger=true"
 - "--tracing.jaeger.gen128Bit=true"
 - "--tracing.jaeger.propagation=b3"
 - "--tracing.jaeger.traceContextHeaderName=b3"
 - "--tracing.jaeger.collector.endpoint=http://collector.linkerd-jaeger:55678"
 - "--tracing.jaeger.collector.user=collector"
