apiVersion: v1
kind: Namespace
metadata:
  name: fluentbit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
  namespace: fluentbit
  labels:
    k8s-app: fluentbit
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentbit
  namespace: fluentbit
  labels:
    k8s-app: fluentbit
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentbit
  labels:
    k8s-app: fluentbit
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentbit
  namespace: fluentbit
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentbit
  apiGroup: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
  namespace: fluentbit
data:
  Region: "Dev"
  Zone: "Dev"
  webvLog: "webvdev"
  ngsaLog: "ngsadev"
