apiVersion: v1
kind: Pod
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory

spec:
  containers:
  - name: ds
    imagePullPolicy: Always
    image: k3d-registry.localhost:5000/ngsa:local
    args:
      - --in-memory
      - --prometheus
      - --log-level
      - Warning
      - --request-log-level
      - Information
      - --zone
      - dev
      - --region
      - dev
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "500Mi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  type: NodePort
  selector:
    app: ngsa-memory
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
